import { useState } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Accordion, 
  AccordionContent, 
  AccordionItem, 
  AccordionTrigger 
} from "@/components/ui/accordion";
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";
import { 
  PlayCircle, 
  BookOpen, 
  Users, 
  Award, 
  Database, 
  BarChart3, 
  Share2, 
  CheckCircle, 
  Star,
  ArrowRight,
  Zap,
  Shield,
  Lightbulb
} from "lucide-react";

export default function Landing() {
  const [selectedScreenshot, setSelectedScreenshot] = useState<string | null>(null);

  const features = [
    {
      day: "Day 1",
      title: "FHIR Data Ingestion",
      icon: <Database className="w-6 h-6" />,
      description: "Load synthetic patient bundles, explore FHIR resources, and understand healthcare data structures",
      highlights: ["Synthea patient data", "Resource exploration", "Bundle uploads"]
    },
    {
      day: "Day 2", 
      title: "Transform & Analyze",
      icon: <BarChart3 className="w-6 h-6" />,
      description: "Extract insights using SQL transformations, calculate risk scores, and generate analytics",
      highlights: ["SQL transformations", "Risk calculations", "Data analytics"]
    },
    {
      day: "Day 3",
      title: "Operationalize",
      icon: <Share2 className="w-6 h-6" />,
      description: "Publish insights back to FHIR as structured observations and create shareable mini-apps",
      highlights: ["FHIR observations", "Mini-apps", "Knowledge sharing"]
    }
  ];

  const screenshots = [
    {
      id: "dashboard",
      title: "Interactive Dashboard",
      description: "Track your progress through hands-on labs",
      image: "/api/placeholder/600/400",
      thumbnail: "/api/placeholder/300/200"
    },
    {
      id: "lab",
      title: "Lab Environment", 
      description: "Work with real FHIR servers and synthetic data",
      image: "/api/placeholder/600/400",
      thumbnail: "/api/placeholder/300/200"
    },
    {
      id: "analytics",
      title: "Data Analytics",
      description: "Transform healthcare data into actionable insights",
      image: "/api/placeholder/600/400", 
      thumbnail: "/api/placeholder/300/200"
    }
  ];

  const pricingPlans = [
    {
      name: "Free Trial",
      price: "Free",
      period: "14 days",
      description: "Perfect for exploring FHIR concepts",
      features: [
        "Access to Day 1 labs",
        "Synthetic data playground", 
        "Basic FHIR server access",
        "Community support"
      ],
      cta: "Start Free Trial",
      popular: false,
      variant: "outline" as const
    },
    {
      name: "Bootcamp Basic",
      price: "$299",
      period: "lifetime access",
      description: "Complete FHIR training program",
      features: [
        "All 3-day lab modules",
        "Interactive quizzes",
        "Downloadable certificates",
        "Local FHIR server setup",
        "Email support"
      ],
      cta: "Start Learning",
      popular: true,
      variant: "default" as const
    },
    {
      name: "Bootcamp Plus",
      price: "$599", 
      period: "lifetime access",
      description: "Advanced features for professionals",
      features: [
        "Everything in Basic",
        "1-on-1 instructor sessions",
        "Custom lab environments",
        "Priority support",
        "Team collaboration tools",
        "Advanced analytics"
      ],
      cta: "Go Premium",
      popular: false,
      variant: "outline" as const
    }
  ];

  const faqs = [
    {
      question: "What is FHIR and why is it important?",
      answer: "FHIR (Fast Healthcare Interoperability Resources) is the modern standard for healthcare data exchange. It enables secure, standardized communication between healthcare systems, making it essential for anyone working in health technology."
    },
    {
      question: "Do I need programming experience?",
      answer: "Basic familiarity with APIs and SQL is helpful but not required. Our hands-on approach teaches you through practical exercises with clear explanations at each step."
    },
    {
      question: "What kind of data do we work with?",
      answer: "We exclusively use synthetic patient data generated by Synthea for training. This provides realistic scenarios without any privacy concerns or PHI exposure."
    },
    {
      question: "Can I use my own FHIR server?",
      answer: "Absolutely! While we provide access to public test servers, you can also set up a local FHIR server or connect to your organization's private instance."
    },
    {
      question: "What happens after the bootcamp?",
      answer: "You'll have lifetime access to all materials, a completion certificate, and the practical skills to implement FHIR in real-world scenarios."
    },
    {
      question: "Is there a refund policy?",
      answer: "Yes, we offer a 30-day money-back guarantee if you're not satisfied with the bootcamp content."
    }
  ];

  const testimonials = [
    {
      name: "Dr. Sarah Chen",
      role: "Chief Medical Officer, HealthTech Solutions",
      content: "This bootcamp transformed our team's understanding of FHIR. The hands-on approach made complex concepts accessible.",
      rating: 5
    },
    {
      name: "Michael Rodriguez",
      role: "Health Informatics Specialist",
      content: "Excellent practical training. I went from FHIR novice to confidently implementing solutions in just 3 days.",
      rating: 5
    },
    {
      name: "Jennifer Walsh",
      role: "Software Engineer, MedCore",
      content: "The synthetic data approach was brilliant. We could experiment safely while learning real-world applications.",
      rating: 5
    }
  ];

  const partners = [
    { name: "HL7 FHIR", logo: "/api/placeholder/120/60" },
    { name: "Synthea", logo: "/api/placeholder/120/60" },
    { name: "HAPI FHIR", logo: "/api/placeholder/120/60" },
    { name: "AWS Healthcare", logo: "/api/placeholder/120/60" },
    { name: "Google Cloud", logo: "/api/placeholder/120/60" },
    { name: "Microsoft Azure", logo: "/api/placeholder/120/60" }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-muted">
      {/* Hero Section */}
      <section className="relative py-20 px-4 text-center">
        <div className="max-w-4xl mx-auto">
          <Badge variant="secondary" className="mb-6 px-4 py-2 text-sm">
            <Zap className="w-4 h-4 mr-2" />
            Interactive Healthcare Interoperability Training
          </Badge>
          
          <h1 className="text-5xl lg:text-6xl font-bold mb-6 bg-gradient-to-r from-primary to-blue-600 bg-clip-text text-transparent">
            Master FHIR in 3 Days
          </h1>
          
          <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto leading-relaxed">
            Learn healthcare interoperability through hands-on labs with real FHIR servers, 
            synthetic patient data, and practical transformations that mirror real-world scenarios.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-12">
            <Button size="lg" className="min-w-[200px]" data-testid="cta-start-trial">
              <PlayCircle className="w-5 h-5 mr-2" />
              Start Free Trial
            </Button>
            <Link href="/demo">
              <Button size="lg" variant="outline" className="min-w-[200px]" data-testid="cta-try-demo">
                <Lightbulb className="w-5 h-5 mr-2" />
                Try Live Demo
              </Button>
            </Link>
            <Button size="lg" variant="ghost" className="min-w-[200px]" data-testid="cta-view-curriculum">
              <BookOpen className="w-5 h-5 mr-2" />
              View Curriculum
            </Button>
          </div>

          {/* Quick Stats */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-2xl mx-auto">
            <div className="text-center">
              <div className="text-3xl font-bold text-primary">3</div>
              <div className="text-sm text-muted-foreground">Days to Mastery</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-primary">100%</div>
              <div className="text-sm text-muted-foreground">Hands-on Labs</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold text-primary">1000+</div>
              <div className="text-sm text-muted-foreground">Students Trained</div>
            </div>
          </div>
        </div>
      </section>

      {/* What You'll Learn */}
      <section className="py-20 px-4 bg-muted/30">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">What You'll Learn</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Master the complete FHIR workflow through our proven 3-day methodology
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-16">
            {features.map((feature, index) => (
              <Card key={feature.day} className="relative overflow-hidden group hover:shadow-lg transition-all duration-300">
                <CardHeader>
                  <div className="flex items-center justify-between mb-4">
                    <Badge variant="outline">{feature.day}</Badge>
                    <div className="text-primary">{feature.icon}</div>
                  </div>
                  <CardTitle className="text-xl">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground mb-4">{feature.description}</p>
                  <ul className="space-y-2">
                    {feature.highlights.map((highlight, idx) => (
                      <li key={idx} className="flex items-center text-sm">
                        <CheckCircle className="w-4 h-4 text-green-500 mr-2 flex-shrink-0" />
                        {highlight}
                      </li>
                    ))}
                  </ul>
                </CardContent>
                <div className="absolute inset-0 bg-gradient-to-r from-primary/5 to-blue-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
              </Card>
            ))}
          </div>

          {/* FHIR Loop Visualization */}
          <div className="text-center">
            <h3 className="text-2xl font-semibold mb-8">The Complete FHIR Learning Loop</h3>
            <div className="flex flex-col md:flex-row items-center justify-center gap-8 max-w-4xl mx-auto">
              <div className="flex items-center space-x-4 bg-background rounded-lg p-6 shadow-sm">
                <Database className="w-8 h-8 text-blue-500" />
                <div className="text-left">
                  <div className="font-semibold">Ingest</div>
                  <div className="text-sm text-muted-foreground">Load & Explore</div>
                </div>
              </div>
              <ArrowRight className="w-6 h-6 text-muted-foreground hidden md:block" />
              <div className="flex items-center space-x-4 bg-background rounded-lg p-6 shadow-sm">
                <BarChart3 className="w-8 h-8 text-green-500" />
                <div className="text-left">
                  <div className="font-semibold">Transform</div>
                  <div className="text-sm text-muted-foreground">Analyze & Process</div>
                </div>
              </div>
              <ArrowRight className="w-6 h-6 text-muted-foreground hidden md:block" />
              <div className="flex items-center space-x-4 bg-background rounded-lg p-6 shadow-sm">
                <Share2 className="w-8 h-8 text-purple-500" />
                <div className="text-left">
                  <div className="font-semibold">Operationalize</div>
                  <div className="text-sm text-muted-foreground">Publish & Share</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Interactive Screenshots */}
      <section className="py-20 px-4">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">See It In Action</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Explore our interactive learning environment through these screenshots
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {screenshots.map((screenshot) => (
              <Dialog key={screenshot.id}>
                <DialogTrigger asChild>
                  <Card className="cursor-pointer group hover:shadow-lg transition-all duration-300">
                    <CardContent className="p-0">
                      <div className="relative overflow-hidden rounded-t-lg">
                        <img 
                          src={screenshot.thumbnail} 
                          alt={screenshot.title}
                          className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                        />
                        <div className="absolute inset-0 bg-black/20 group-hover:bg-black/10 transition-colors duration-300" />
                        <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                          <PlayCircle className="w-12 h-12 text-white" />
                        </div>
                      </div>
                      <div className="p-6">
                        <h3 className="font-semibold text-lg mb-2">{screenshot.title}</h3>
                        <p className="text-muted-foreground text-sm">{screenshot.description}</p>
                      </div>
                    </CardContent>
                  </Card>
                </DialogTrigger>
                <DialogContent className="max-w-4xl w-full">
                  <img 
                    src={screenshot.image} 
                    alt={screenshot.title}
                    className="w-full rounded-lg"
                  />
                </DialogContent>
              </Dialog>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-20 px-4 bg-muted/30">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Choose Your Learning Path</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Start with our free trial or jump into the complete bootcamp experience
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {pricingPlans.map((plan) => (
              <Card key={plan.name} className={`relative ${plan.popular ? 'ring-2 ring-primary shadow-lg scale-105' : ''}`}>
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 transform -translate-x-1/2">
                    <Badge className="bg-primary text-primary-foreground px-4 py-1">Most Popular</Badge>
                  </div>
                )}
                <CardHeader className="text-center pb-4">
                  <CardTitle className="text-2xl">{plan.name}</CardTitle>
                  <div className="mt-4">
                    <span className="text-4xl font-bold">{plan.price}</span>
                    <span className="text-muted-foreground ml-2">/ {plan.period}</span>
                  </div>
                  <p className="text-muted-foreground mt-2">{plan.description}</p>
                </CardHeader>
                <CardContent className="space-y-6">
                  <ul className="space-y-3">
                    {plan.features.map((feature, idx) => (
                      <li key={idx} className="flex items-center">
                        <CheckCircle className="w-5 h-5 text-green-500 mr-3 flex-shrink-0" />
                        <span className="text-sm">{feature}</span>
                      </li>
                    ))}
                  </ul>
                  <Button className="w-full" variant={plan.variant} size="lg">
                    {plan.cta}
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="py-20 px-4">
        <div className="max-w-6xl mx-auto">
          {/* Partners */}
          <div className="text-center mb-16">
            <h3 className="text-lg font-semibold text-muted-foreground mb-8">Trusted by Healthcare Technology Leaders</h3>
            <div className="grid grid-cols-2 md:grid-cols-6 gap-8 items-center opacity-60">
              {partners.map((partner, idx) => (
                <div key={idx} className="flex items-center justify-center">
                  <img src={partner.logo} alt={partner.name} className="h-12 object-contain filter grayscale" />
                </div>
              ))}
            </div>
          </div>

          {/* Testimonials */}
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold mb-4">What Our Students Say</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Real feedback from healthcare professionals who've completed our bootcamp
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, idx) => (
              <Card key={idx} className="h-full">
                <CardContent className="p-6">
                  <div className="flex items-center mb-4">
                    {Array.from({ length: testimonial.rating }).map((_, i) => (
                      <Star key={i} className="w-4 h-4 fill-yellow-400 text-yellow-400" />
                    ))}
                  </div>
                  <p className="text-muted-foreground mb-4 italic">"{testimonial.content}"</p>
                  <div>
                    <div className="font-semibold">{testimonial.name}</div>
                    <div className="text-sm text-muted-foreground">{testimonial.role}</div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 px-4 bg-muted/30">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Frequently Asked Questions</h2>
            <p className="text-xl text-muted-foreground">
              Get answers to common questions about our FHIR bootcamp
            </p>
          </div>

          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, idx) => (
              <AccordionItem key={idx} value={`item-${idx}`} className="bg-background rounded-lg px-6">
                <AccordionTrigger className="text-left font-semibold">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-muted-foreground">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-4 text-center">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-4xl font-bold mb-6">Ready to Master FHIR?</h2>
          <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
            Join thousands of healthcare professionals who've transformed their careers with practical FHIR skills
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" className="min-w-[200px]">
              <PlayCircle className="w-5 h-5 mr-2" />
              Start Free Trial
            </Button>
            <Button size="lg" variant="outline" className="min-w-[200px]">
              <Users className="w-5 h-5 mr-2" />
              Contact Sales
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-background border-t">
        <div className="max-w-6xl mx-auto py-12 px-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-8">
            <div>
              <h3 className="font-semibold mb-4">Learning</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/curriculum" className="hover:text-primary">Curriculum</Link></li>
                <li><Link href="/demo" className="hover:text-primary">Demo</Link></li>
                <li><Link href="/docs" className="hover:text-primary">Documentation</Link></li>
                <li><Link href="/resources" className="hover:text-primary">Resources</Link></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Pricing</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/pricing" className="hover:text-primary">Plans</Link></li>
                <li><Link href="/enterprise" className="hover:text-primary">Enterprise</Link></li>
                <li><Link href="/nonprofit" className="hover:text-primary">Nonprofit</Link></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Support</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/help" className="hover:text-primary">Help Center</Link></li>
                <li><Link href="/contact" className="hover:text-primary">Contact</Link></li>
                <li><Link href="/community" className="hover:text-primary">Community</Link></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Legal</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link href="/terms" className="hover:text-primary">Terms</Link></li>
                <li><Link href="/privacy" className="hover:text-primary">Privacy</Link></li>
                <li><Link href="/security" className="hover:text-primary">Security</Link></li>
              </ul>
            </div>
          </div>
          
          <div className="flex flex-col md:flex-row justify-between items-center pt-8 border-t">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <Shield className="w-6 h-6 text-primary" />
              <span className="font-semibold">FHIR Healthcare Bootcamp</span>
            </div>
            <div className="text-sm text-muted-foreground">
              © 2024 FHIR Healthcare Bootcamp. All rights reserved.
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}