import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Separator } from "@/components/ui/separator";
import { Link } from "wouter";
import { Shield, Lock, Server, AlertTriangle, CheckCircle, Database, Globe, Monitor, Mail } from "lucide-react";

export default function Security() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-muted">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold mb-4 flex items-center justify-center gap-2">
              <Shield className="h-8 w-8 text-primary" />
              Security Policy
            </h1>
            <p className="text-xl text-muted-foreground">
              Data protection and security practices for FHIR Healthcare Bootcamp
            </p>
          </div>

          {/* PHI Policy Alert */}
          <Alert className="mb-8 bg-red-50 dark:bg-red-950 border-red-200 dark:border-red-800">
            <AlertTriangle className="h-4 w-4 text-red-600" />
            <AlertDescription className="text-red-800 dark:text-red-200">
              <strong>Critical Policy: No PHI on Public Servers</strong><br />
              Protected Health Information (PHI) or real patient data must NEVER be uploaded to public FHIR test servers. 
              Our platform exclusively uses synthetic data for training purposes. For any real data work, use Local HAPI setup only.
            </AlertDescription>
          </Alert>

          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Database className="h-5 w-5" />
                  PHI Protection Policy
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="bg-green-50 dark:bg-green-950 border border-green-200 dark:border-green-800 rounded-lg p-4">
                  <h3 className="font-semibold text-green-900 dark:text-green-100 mb-2 flex items-center gap-2">
                    <CheckCircle className="h-4 w-4" />
                    Synthetic Data Only
                  </h3>
                  <p className="text-green-800 dark:text-green-200">
                    All training exercises use exclusively synthetic patient data generated by Synthea. This data is completely artificial, HIPAA-compliant, and safe for educational use on public FHIR servers.
                  </p>
                </div>

                <div className="bg-red-50 dark:bg-red-950 border border-red-200 dark:border-red-800 rounded-lg p-4">
                  <h3 className="font-semibold text-red-900 dark:text-red-100 mb-2 flex items-center gap-2">
                    <AlertTriangle className="h-4 w-4" />
                    Prohibited: Real Patient Data
                  </h3>
                  <ul className="text-red-800 dark:text-red-200 space-y-1 list-disc list-inside">
                    <li>Never upload real patient data to public test servers</li>
                    <li>Do not use production FHIR servers for training exercises</li>
                    <li>Avoid any data that could identify real individuals</li>
                    <li>Report any suspected PHI exposure immediately</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">Data Classification Guidelines</h3>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                      <span className="text-sm"><strong>Safe:</strong> Synthea synthetic data, anonymized datasets, test data</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                      <span className="text-sm"><strong>Prohibited:</strong> Real patient records, production data, identifiable information</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Server className="h-5 w-5" />
                  Local HAPI FHIR Server Guidance
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                  <h3 className="font-semibold text-blue-900 dark:text-blue-100 mb-2">Recommended for Real Data Work</h3>
                  <p className="text-blue-800 dark:text-blue-200">
                    For any work involving real healthcare data or production scenarios, we strongly recommend setting up a local HAPI FHIR server. This ensures complete data control and compliance with your organization's security policies.
                  </p>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">Local Setup Benefits</h3>
                  <ul className="list-disc list-inside space-y-1 ml-4">
                    <li><strong>Complete Control:</strong> Full control over data storage and access</li>
                    <li><strong>Privacy:</strong> Data never leaves your local environment</li>
                    <li><strong>Compliance:</strong> Easier to meet organizational security requirements</li>
                    <li><strong>Testing:</strong> Safe environment for real-world scenarios</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">Setup Instructions</h3>
                  <ol className="list-decimal list-inside space-y-1 ml-4">
                    <li>Download HAPI FHIR server from official repository</li>
                    <li>Configure server settings for your security requirements</li>
                    <li>Set up appropriate access controls and authentication</li>
                    <li>Configure our platform to connect to your local server</li>
                    <li>Verify connection and test with synthetic data first</li>
                  </ol>
                </div>

                <Alert>
                  <Monitor className="h-4 w-4" />
                  <AlertDescription>
                    <strong>Note:</strong> Our platform supports both public test servers (for synthetic data only) and private local servers (for any data type). Always configure the appropriate server type for your use case.
                  </AlertDescription>
                </Alert>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Lock className="h-5 w-5" />
                  Platform Security Measures
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h3 className="font-semibold mb-2">Data Encryption</h3>
                  <ul className="list-disc list-inside space-y-1 ml-4">
                    <li>All data transmitted using TLS 1.3 encryption</li>
                    <li>Data at rest encrypted using AES-256</li>
                    <li>End-to-end encryption for sensitive communications</li>
                    <li>Regular encryption key rotation</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">Access Controls</h3>
                  <ul className="list-disc list-inside space-y-1 ml-4">
                    <li>Multi-factor authentication for all accounts</li>
                    <li>Role-based access control (RBAC)</li>
                    <li>Session management with automatic timeouts</li>
                    <li>Regular access reviews and audits</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">Infrastructure Security</h3>
                  <ul className="list-disc list-inside space-y-1 ml-4">
                    <li>Cloud infrastructure with SOC 2 Type II compliance</li>
                    <li>Web Application Firewall (WAF) protection</li>
                    <li>DDoS protection and monitoring</li>
                    <li>Regular security patches and updates</li>
                    <li>Intrusion detection and response systems</li>
                  </ul>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Compliance and Certifications</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid md:grid-cols-2 gap-4">
                  <div>
                    <h3 className="font-semibold mb-2">Healthcare Compliance</h3>
                    <ul className="list-disc list-inside space-y-1 text-sm ml-4">
                      <li>HIPAA Security Rule alignment</li>
                      <li>GDPR compliance for EU users</li>
                      <li>CCPA compliance for California residents</li>
                      <li>HL7 FHIR R4 standard implementation</li>
                    </ul>
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2">Security Standards</h3>
                    <ul className="list-disc list-inside space-y-1 text-sm ml-4">
                      <li>SOC 2 Type II compliance</li>
                      <li>ISO 27001 security framework</li>
                      <li>OWASP Top 10 protection</li>
                      <li>Regular penetration testing</li>
                    </ul>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>FHIR Server Security Guidelines</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h3 className="font-semibold mb-2">Public Test Servers</h3>
                  <div className="bg-yellow-50 dark:bg-yellow-950 border border-yellow-200 dark:border-yellow-800 rounded-lg p-3">
                    <p className="text-yellow-800 dark:text-yellow-200 text-sm">
                      <strong>Use Only For:</strong> Synthetic data, training exercises, proof-of-concept work
                    </p>
                  </div>
                  <ul className="list-disc list-inside space-y-1 ml-4 mt-2">
                    <li>HAPI FHIR test server (test.fhir.org)</li>
                    <li>Medplum development server</li>
                    <li>Other publicly accessible test servers</li>
                    <li>Always assume data is publicly visible</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">Private/Local Servers</h3>
                  <div className="bg-green-50 dark:bg-green-950 border border-green-200 dark:border-green-800 rounded-lg p-3">
                    <p className="text-green-800 dark:text-green-200 text-sm">
                      <strong>Approved For:</strong> Any data type, production work, real healthcare scenarios
                    </p>
                  </div>
                  <ul className="list-disc list-inside space-y-1 ml-4 mt-2">
                    <li>Local HAPI FHIR installations</li>
                    <li>Organization-hosted FHIR servers</li>
                    <li>Private cloud instances</li>
                    <li>Development environments with proper security</li>
                  </ul>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Incident Response</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h3 className="font-semibold mb-2">Security Incident Reporting</h3>
                  <p className="mb-2">If you discover a security vulnerability or incident:</p>
                  <ul className="list-disc list-inside space-y-1 ml-4">
                    <li>Report immediately to our security team</li>
                    <li>Do not attempt to exploit or further investigate</li>
                    <li>Preserve any evidence if safe to do so</li>
                    <li>Follow responsible disclosure practices</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">PHI Exposure Response</h3>
                  <p className="mb-2">If PHI is accidentally uploaded or exposed:</p>
                  <ol className="list-decimal list-inside space-y-1 ml-4">
                    <li>Immediately stop the activity and disconnect</li>
                    <li>Document what happened and what data was involved</li>
                    <li>Contact our security team immediately</li>
                    <li>Follow your organization's breach notification procedures</li>
                    <li>Cooperate with investigation and remediation efforts</li>
                  </ol>
                </div>

                <Alert className="bg-red-50 dark:bg-red-950 border-red-200 dark:border-red-800">
                  <AlertTriangle className="h-4 w-4 text-red-600" />
                  <AlertDescription className="text-red-800 dark:text-red-200">
                    <strong>Emergency Contact:</strong> For immediate security concerns, contact{" "}
                    <a href="mailto:security@fhirbootcamp.com" className="underline font-semibold">
                      security@fhirbootcamp.com
                    </a>
                  </AlertDescription>
                </Alert>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>User Responsibilities</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h3 className="font-semibold mb-2">Account Security</h3>
                  <ul className="list-disc list-inside space-y-1 ml-4">
                    <li>Use strong, unique passwords</li>
                    <li>Enable multi-factor authentication</li>
                    <li>Keep login credentials confidential</li>
                    <li>Log out from shared or public computers</li>
                    <li>Report suspicious activity immediately</li>
                  </ul>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">Data Handling</h3>
                  <ul className="list-disc list-inside space-y-1 ml-4">
                    <li>Only use synthetic data on public servers</li>
                    <li>Verify data type before upload</li>
                    <li>Follow your organization's data policies</li>
                    <li>Understand FHIR server security settings</li>
                    <li>Report any data concerns promptly</li>
                  </ul>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Contact Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid md:grid-cols-2 gap-4">
                  <div>
                    <h3 className="font-semibold mb-2">Security Team</h3>
                    <div className="space-y-2 text-sm">
                      <div className="flex items-center gap-2">
                        <Mail className="h-4 w-4" />
                        <a href="mailto:security@fhirbootcamp.com" className="text-primary hover:underline">
                          security@fhirbootcamp.com
                        </a>
                      </div>
                      <p className="text-muted-foreground">For security incidents and vulnerabilities</p>
                    </div>
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2">Compliance Officer</h3>
                    <div className="space-y-2 text-sm">
                      <div className="flex items-center gap-2">
                        <Mail className="h-4 w-4" />
                        <a href="mailto:compliance@fhirbootcamp.com" className="text-primary hover:underline">
                          compliance@fhirbootcamp.com
                        </a>
                      </div>
                      <p className="text-muted-foreground">For compliance and policy questions</p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          <Separator className="my-8" />

          <div className="text-center text-sm text-muted-foreground">
            <p className="mb-2">
              This security policy is effective as of January 15, 2024.
            </p>
            <div className="flex justify-center gap-4">
              <Link href="/terms" className="hover:text-primary">Terms of Service</Link>
              <Link href="/privacy" className="hover:text-primary">Privacy Policy</Link>
              <Link href="/help" className="hover:text-primary">Help Center</Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}