import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Link } from "wouter";
import { Shield, FileText, Calendar, Mail } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-muted">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold mb-4 flex items-center justify-center gap-2">
              <FileText className="h-8 w-8 text-primary" />
              Terms of Service
            </h1>
            <p className="text-xl text-muted-foreground">
              Last updated: January 15, 2024
            </p>
          </div>

          <Card className="mb-8">
            <CardHeader>
              <CardTitle>Agreement to Terms</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>
                By accessing and using the FHIR Healthcare Bootcamp platform ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these terms, you may not access the Service.
              </p>
              <p>
                These Terms apply to all visitors, users, and others who access or use the Service.
              </p>
            </CardContent>
          </Card>

          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>1. Use License</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  Permission is granted to temporarily access the materials on FHIR Healthcare Bootcamp for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>modify or copy the materials</li>
                  <li>use the materials for any commercial purpose or for any public display</li>
                  <li>attempt to reverse engineer any software contained on the platform</li>
                  <li>remove any copyright or other proprietary notations from the materials</li>
                </ul>
                <p>
                  This license shall automatically terminate if you violate any of these restrictions and may be terminated by us at any time.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>2. Educational Content and Synthetic Data</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  Our educational platform uses exclusively synthetic patient data generated by Synthea and other approved synthetic data generators. This data is:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Completely artificial and does not represent real patients</li>
                  <li>Safe for educational and training purposes</li>
                  <li>Compliant with healthcare privacy regulations</li>
                  <li>Free from Protected Health Information (PHI)</li>
                </ul>
                <p>
                  Students are prohibited from uploading, processing, or storing any real patient data or PHI on public FHIR servers through our platform.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>3. User Accounts and Responsibilities</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  When you create an account with us, you must provide information that is accurate, complete, and current at all times. You are responsible for:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Safeguarding the password and all activities under your account</li>
                  <li>Notifying us immediately of any unauthorized use</li>
                  <li>Ensuring compliance with healthcare data regulations in your jurisdiction</li>
                  <li>Using the platform only for legitimate educational purposes</li>
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>4. Payment and Refunds</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  Paid courses and bootcamp access are subject to the following terms:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Payment is required before accessing paid content</li>
                  <li>We offer a 30-day money-back guarantee for bootcamp purchases</li>
                  <li>Refund requests must be submitted through our support channels</li>
                  <li>Access to paid content will be revoked upon successful refund processing</li>
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>5. Privacy and Data Protection</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information when you use our Service. By using our Service, you agree to the collection and use of information in accordance with our Privacy Policy.
                </p>
                <p>
                  We are committed to maintaining the confidentiality and security of any personal information you provide to us.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>6. Prohibited Uses</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  You may not use our Service:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>For any unlawful purpose or to solicit others to unlawful acts</li>
                  <li>To violate any international, federal, provincial, or state regulations or laws</li>
                  <li>To transmit, or procure the sending of, any advertising or promotional material</li>
                  <li>To impersonate or attempt to impersonate the company, employees, or other users</li>
                  <li>To upload or process any real patient data or PHI</li>
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>7. Disclaimer</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  The information on this platform is provided on an 'as is' basis. To the fullest extent permitted by law, FHIR Healthcare Bootcamp excludes all representations, warranties, conditions and other terms which might otherwise be implied by statute, common law, or the law of equity.
                </p>
                <p>
                  The educational content is for training purposes only and should not be used as a substitute for professional medical advice, diagnosis, or treatment.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>8. Limitations</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  In no event shall FHIR Healthcare Bootcamp or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on the platform, even if we or our authorized representative has been notified orally or in writing of the possibility of such damage.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>9. Changes to Terms</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect.
                </p>
                <p>
                  What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>10. Contact Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <p>
                  If you have any questions about these Terms of Service, please contact us:
                </p>
                <div className="flex items-center gap-2 text-sm">
                  <Mail className="h-4 w-4" />
                  <a href="mailto:legal@fhirbootcamp.com" className="text-primary hover:underline">
                    legal@fhirbootcamp.com
                  </a>
                </div>
              </CardContent>
            </Card>
          </div>

          <Separator className="my-8" />

          <div className="text-center text-sm text-muted-foreground">
            <p className="mb-2">
              These terms are effective as of January 15, 2024.
            </p>
            <div className="flex justify-center gap-4">
              <Link href="/privacy" className="hover:text-primary">Privacy Policy</Link>
              <Link href="/security" className="hover:text-primary">Security Policy</Link>
              <Link href="/help" className="hover:text-primary">Help Center</Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}